Bookers/config/routes.rb
Rails.application.routes.draw do
  # temporary create this routes => root 'users#show'
  root 'homes#index'
  get "/home/about" => "homes#about"
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :homes, only: [:new, :index]
  resources :users, only: [:show, :index, :edit, :update]
  resources :books
end

Bookers/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Bookers/app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: {maximum:200}
end

Bookers/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :user_profile, dependent: :destroy
  has_many :books, dependent: :destroy
  attachment :profile_image

  validates :name, uniqueness: true
  validates :name, presence: true
  validates :name, length: { in: 2..20}
  validates :introduction, length: { maximum:50 }

  def email_required?
    false
  end
  def email_changed
    false
  end
end

Bookers/app/controllers/application_controller.rb
# class ApplicationController < ActionController::Base
#     before_action :authenticate_user!, except: [:new]
#     before_action :configure_permitted_parameters, if: :devise_controller?

#   protected
#    def configure_permitted_parameters
#      added_attrs = [ :email, :name, :password, :password_confirmation ]
#      devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
#      devise_parameter_sanitizer.permit :account_update, keys: added_attrs
#      devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
#    end

#    def after_sign_in_path_for(resource)
#      user_path(current_user.id)
#    end
# end




class ApplicationController < ActionController::Base
      before_action :authenticate_user!, except: [:new]

 # 下記を追加
 before_action :configure_permitted_parameters, if: :devise_controller?

 protected
 def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
   devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
   devise_parameter_sanitizer.permit(:account_update, keys: [:name])
 end

    def after_sign_in_path_for(resource)
     user_path(current_user.id)
   end
end

Bookers/app/controllers/books_controller.rb
class BooksController < ApplicationController

def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "successfully"
      redirect_to book_path(@book)
    else
      @user = User.find(current_user.id)
      flash[:errors] = @book.errors.full_messages
      redirect_to books_path
    end
  end

  def show
    #to show the book details
    @book = Book.new
    @detail_book = Book.find(params[:id])
    @user = @detail_book.user
  end

  def index
  	@user = User.find(current_user.id)
    #to create book post
    @book = Book.new
    #To show all book posts
    @books = Book.all
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user.id != current_user.id
      flash[:notice] = "You don't have the right to edit it"
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to book_path(@book)
    else
      # flash[:errors] = book.errors.full_messages
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    flash[:notice] = "Book was successfully deleted."
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

Bookers/app/controllers/homes_controller.rb
class HomesController < ApplicationController
	skip_before_action :authenticate_user!
  def new
  end

  def index
  end
end

Bookers/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @user = User.find(current_user.id)
    @users = User.all
    @book = Book.new
  end

  def edit
  	@user = User.find(params[:id])
        if current_user.id != @user.id
          redirect_to user_path(current_user)
        end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "successfully"
      redirect_to user_path(@user)
    else
      # flash[:errors] = @user.errors.full_messages
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

Bookers/app/helpers/application_helper.rb
module ApplicationHelper
end

Bookers/app/helpers/books_helper.rb
module BooksHelper
end

Bookers/app/helpers/homes_helper.rb
module HomesHelper
end

Bookers/app/helpers/users_helper.rb
module UsersHelper
end

Bookers/app/views/books/edit.html.erb
<section class="sct-color-1 slice">
  <div class="container-fluid masonry-container">
<div class="row">
  <div class="col-sm-4 col-sm-offset-4">
  <% if @book.errors.any? %>
    <%= @book.errors.count %>error<br>
    <% @book.errors.full_messages.each do |message| %>
      <%= message %><br>
    <% end %>
  <% end %>
  <%= form_for(@book) do |f| %>
    <div class="form-group has-icon">
      <label class="control-label sr-only">Title</label>
      <%= f.text_field :title, class:"form-control book_title", placeholder:"Book Title" %>
      <span class="fa fa-building form-control-icon" aria-hidden="true" ></span>
    </div>
    <div class="form-group has-icon">
      <label class="control-label sr-only">Opinion</label>
      <%= f.text_area :body, class:"form-control book_body", placeholder:"Your opinion about Book" %>
      <span class="fa fa-building form-control-icon" aria-hidden="true" ></span>
    </div>
    <%= f.submit "Edit it", class:"btn btn-primary btn-block btn-base-1 mt-20" %>
  <% end %>
  <%= link_to "Show", book_path(@book), class:"edit_book_#{@book.id}" %>
  |
  <%= link_to "Back", books_path, class:"books" %>
  </div>
</div>
</div>
</section>

Bookers/app/views/books/index.html.erb
<section class="sct-color-1 slice">
  <div class="container-fluid masonry-container">
  <div class="row">
    <%= render 'users/userInfo', {user: @user, book: @book} %>
    <div class="col-sm-6">
      <h1>Books</h1>
      <table class="table table-striped">
        <tr>
          <th>User</th>
          <th>Title</th>
          <th>Opinion</th>
        </tr>
        <% @books.each do |book| %>
        <tr>
          <td><%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, format:'jpeg', class:"img-circle pull-left profile-img", fallback:"no_image.jpg" %></td>
          <td><%= link_to "#{book.title}", book_path(book), class:"book_#{book.id}" %></td>
          <td><%= book.body %></td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>
</section>

Bookers/app/views/books/show.html.erb
<section class="sct-color-1 slice">
  <div class="container-fluid masonry-container">
  <div class="row">
    <%= render 'users/userInfo', {user: @user, book: @book} %>
<div class="col-sm-6">
  <h1>Book Details</h1>
  <table class="table table-striped">
    <tr>
      <th>User</th>
      <th>Title</th>
      <th>Opinion</th>
      <% if @detail_book.user.id == current_user.id %>
      <th></th>
      <th></th>
      <% end %>
    </tr>
    <tr>
      <td>
        <!-- insert profile_image and link_to user_profile -->
        <%= attachment_image_tag @detail_book.user, :profile_image, :fill, 60, 60, format:'jpeg', class:"img-circle pull-left profile-img", fallback:"no_image.jpg" %>
      </td>
      <td><%= @detail_book.title %></td>
      <td><%= @detail_book.body %></td>
      <% if @detail_book.user.id == current_user.id %>
      <td><%= link_to "Edit", edit_book_path(@detail_book), class:"edit_book_#{@detail_book.id}" "btn btn-success" %>

</td>

      <td><%= link_to "delete", book_path(@detail_book), method: :delete, class:"destroy_book_#{@detail_book.id}" "btn btn-danger" %></td>
      <% end %>
    </tr>
  </table>
  <%= link_to "#{@detail_book.user.name}", user_path(@detail_book.user), class:"user_#{@detail_book.user.id}" %>
</div>
</div>
</div>
</section>

Bookers/app/views/homes/about.html.erb
<section class="sct-color-1 slice">
 <div class="container-fluid masonry-container">
  <div class="row">
   <div class="col-sm-7 col-sm-offset-4">
    <h1>Welcome to Bookers!</h1>

   </div>
  </div>
 </div>
</section>

Bookers/app/views/homes/index.html.erb
<section class="sct-color-1 slice">
<div class="container-fluid masonry-container">
<div class="row">
<div class="col-sm-7 col-sm-offset-4">
  <h1>welcome to Bookers !!</h1>
  <p>In Bookers,</p>

  <p>you can share and exchange your opinions , inpressions , and emotions</p>
  <p>about varioius books!</p>
  <div class="row">
    <div class="col-sm-7">
    <%= link_to "SignUp", new_user_registration_path, class:"btn btn-block btn-info sign_up" %>
    <%= link_to "LogIn", new_user_session_path, class:"btn btn-block btn-success sign_in" %>
    </div>
  </div>
</div>
</div>
</div>
</section>

Bookers/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


<body>
<div class="header" id="header">
  <nav class="navbar navbar-inverse navbar-main navbar-shadow" role="navigation" id="slide-nav">
    <div class="container relative">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Bookers</a>
    </div>
          <div class="sidemenu">
            <ul class="nav navbar-nav navbar-right" data-hover="dropdown" data-animations="zoomIn fadeIn fadeInUp fadeIn">
              <% if user_signed_in? %>
                <li class="">
                  <%=link_to "Home", user_path(current_user), class:"home glyphicon glyphicon-home" %>
                </li>
                <li class="">
                  <%=link_to "Users", users_path, class:"users glyphicon glyphicon-user" %>
                </li>
                <li class="">
                  <%=link_to "Books", books_path, class:"books glyphicon glyphicon-book" %>
                </li>
                <li class="">
                  <%=link_to "logout", destroy_user_session_path, method: :delete, class:"logout glyphicon glyphicon-log-out" %>
                </li>
              <% else %>
                <li class="">
                  <%=link_to "Home", root_path, class:"home glyphicon glyphicon-home" %>
                </li>
                <li class="">
                  <%=link_to "About", "/home/about", class:"about glyphicon glyphicon-link" %>
                </li>
                <li class="">
                  <%= link_to "sign up", new_user_registration_path, class:"sign_up glyphicon glyphicon-edit" %>
                </li>
                <li class="">
                  <%= link_to "login", new_user_session_path, class:"sign_in glyphicon glyphicon-log-in" %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </div>
    <% if flash[:notice] %>
    <div class="row">
      <div class="col-sm-4 col-sm-offset-4">
      <div class="notice">
        <%= flash[:notice] %>
      </div>
      </div>
    </div>
    <% end %>
    <% if flash[:errors] %>
    <div class="row">
      <div class="col-sm-4 col-sm-offset-4">
      <div class="notice">
        <%= flash[:errors].count %>error<br>
        <% flash[:errors].each do |error| %>
          <%= error %><br>
        <% end %>
      </div>
      </div>
    </div>
    <% end %>


    <%= yield %>
  </body>
</html>

Bookers/app/views/users/_userInfo.html.erb
<div class="col-sm-2 col-sm-offset-1">
  <!--  depending upon user, change userProfile -->
  <% if current_user.id == user.id %>
  <div class="row">
    <h1>User Info</h1>
    <%= attachment_image_tag current_user, :profile_image, :fill, 60, 60, format:'jpeg', class:"img-circle pull-left profile-img", fallback:"no_image.jpg" %>
    <table class="table">
      <tr>
        <th>name</th>
        <th><%= current_user.name %></th>
      </tr>
      <tr>
        <th>Introduction</th>
        <th><%= current_user.introduction %></th>
      </tr>
    </table>
      <%= link_to(edit_user_path(user), class:"btn btn-default btn-block edit_user_#{current_user.id}") do %>
      <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
      <% end %>
  </div>
  <% else %>
  <div class="row">
    <h1>UserInfo</h1>
    <%= attachment_image_tag user, :profile_image, :fill, 60, 60, format:'jpeg', class:"img-circle pull-left profile-img", fallback:"no_image.jpg" %>
    <table class="table">
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>Introduction</th>
        <th><%= user.introduction %></th>
      </tr>
    </table>
  </div>
  <% end %>
  <div class="row">
  <%= form_for(book) do |f| %>
  <h1>New Book</h1>
    <div class="form-group has-icon">
      <label class="control-label sr-only">Title</label>
      <%= f.text_field :title, class:"form-control book_title", placeholder:"Book Title" %>
      <span class="fa fa-building form-control-icon" aria-hidden="true" ></span>
    </div>
    <div class="form-group has-icon">
      <label class="control-label sr-only">Opinion</label>
      <%= f.text_area :body, class:"form-control book_body", placeholder:"Your opinion about Book" %>
      <span class="fa fa-building form-control-icon" aria-hidden="true" ></span>
    </div>
    <%= f.submit "Post it", class:"btn btn-primary btn-block btn-base-1 mt-20" %>
  <% end %>
  </div>
</div>

Bookers/app/views/users/edit.html.erb
<section class="sct-color-1 slice">
<div class="container-fluid masonry-container">
<div class="row">
<div class="col-sm-2 col-sm-offset-1">
  <div class="row">
    <% if @user.errors.any? %>
      <%= @user.errors.count %> error<br>
      <%= @user.errors.full_messages.each do |message| %>
        <%= message %><br>
      <% end %>
    <% end %>
    <%= form_for(@user) do |f| %>
    <h1>UserInfo</h1>
      <div class="form-group has-icon">
        <label class="control-label sr-only" for="inputEmail">Name</label>
        <%= f.text_field :name, class:"form-control name", placeholder:"Name" %>
        <span class="fa fa-building form-control-icon" aria-hidden="true" ></span>
      </div>
      <div class="form-group has-icon">

        <label class="control-label sr-only" for="inputEmail">ProfileImage</label>
        <%= f.attachment_field :profile_image, class:"user_image", placeholder:"ProfileImage", class:"user-edit-form" %>
      </div>
      <div class="form-group has-icon">
        <label class="control-label sr-only">Introduction</label>
        <%= f.text_area :introduction, class:"form-control introduction", placeholder:"Your Introduction" %>
        <span class="fa fa-building form-control-icon" aria-hidden="true" ></span>
      </div>
      <%= f.submit "Update User", class:"btn btn-default btn-block btn-base-1 mt-20" %>
    <% end %>
  </div>
</div>
</div>
</div>
</section>

Bookers/app/views/users/index.html.erb
<section class="sct-color-1 slice">
  <div class="container-fluid masonry-container">
<div class="row">
<%= render 'users/userInfo', {user: @user, book: @book} %>
<div class="col-sm-6">
  <h1>Users</h1>
  <table class="table table-striped">
    <tr>
      <th>Image</th>
      <th>Name</th>
      <th></th>
    </tr>
    <% @users.each do |user| %>
    <tr>
      <td><%= attachment_image_tag user, :profile_image, :fill, 60, 60, format:'jpeg', class:"img-circle pull-left profile-img", fallback:"no_image.jpg" %></td>
      <td><%= user.name %></td>
      <td><%= link_to "Show", user_path(user), class:"user_#{user.id}" %></td>
    </tr>
    <% end %>
  </table>
</div>
</div>
  </div>
</section>
</div>
</div>
</div>
</section>

Bookers/app/views/users/show.html.erb
<section class="sct-color-1 slice">
  <div class="container-fluid masonry-container">
  <div class="row">
    <%= render 'users/userInfo', {user: @user, book: @book} %>
<div class="col-sm-6">
  <h1>Books</h1>
  <table class="table table-striped">
    <tr>
      <th>Title</th>
      <th>Opinion</th>
    </tr>
    <% @books.each do |book| %>
    <tr>

      <td><%= link_to "#{book.title}", book_path(book), class:"book_#{book.id}" %></td>
      <td><%= book.body %></td>
    </tr>
    <% end %>
  </table>
</div>
</div>
</div>
</section>